### PR TITLE
Fetch new data on route change

### PR DESCRIPTION
**Pull request by benjick**

### CODE REVIEW

**Comment by zimme** [comment]
Do we really want to unconditionally refetch on route change? I can see it for the case when we're in editor mode, but for the normal case I'm not completely sure...

**Comment by benjick** [comment]
@zimme Yes, but we have to handle it somehow when we support multiple paths

**Comment by benjick** [comment]
Currently if you go from `/` to `/test` we don't get new content

**Comment by zimme** [comment]
> Currently if you go from `/` to `/test` we don't get new content

I believe I might have fixed that in #44, if you look at the commits in there about the reactivity.
Maybe it's needed to set a key on the `router-view` as you've done in this PR to make sure each route
get's it's own instance of the `Storyblok` page component

**Comment by zimme** [comment]
But I believe the fetching already happens in mounted if there isn't a `this.story` based on editor mode's storyId or the url path.

**Comment by benjick** [comment]
@zimme are you ready to merge that PR?

**Comment by zimme** [comment]
> @zimme are you ready to merge that PR?

Yeah, just double checking locally that things actually work before merging =)

**Pull request closed without merging**
